# Generated by Django 2.2.1 on 2020-08-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_auto_20200816_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('expected_end_date', models.DateField(verbose_name='Expected End Date')),
                ('status', models.CharField(choices=[('on_going', 'On Going'), ('on_hold', 'On Hold'), ('success', 'Success'), ('canceled', 'Canceled')], max_length=20)),
                ('progress', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client Company')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
