# Generated by Django 2.2.1 on 2020-08-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('on_going', 'On Going'), ('on_hold', 'On Hold'), ('success', 'Success'), ('canceled', 'Canceled')], default='Started', max_length=20, null=True),
        ),
    ]
