# Generated by Django 3.1.7 on 2021-03-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='remarks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
