# Generated by Django 3.1.7 on 2021-03-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210311_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.segment'),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='field_manager_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.user'),
        ),
    ]
