# Generated by Django 3.1.7 on 2021-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_wage_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
