# Generated by Django 3.1.7 on 2021-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210317_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
