# Generated by Django 3.1.7 on 2021-03-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210311_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='gm_comment',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='manager_comment',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='project_manager_comment',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
