# Generated by Django 2.2.1 on 2020-08-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_ductsystem_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ductsystem',
            name='duct_code',
            field=models.CharField(default='DC', max_length=15),
        ),
    ]
