# Generated by Django 2.2.1 on 2020-08-23 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_ductsystem_duct_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='ProjectWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('central', 'Central'), ('northern', 'Northern'), ('southern', 'Southern'), ('western', 'Western'), ('eastern', 'Eastern')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_measure', models.CharField(max_length=50)),
                ('client_segmate', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectType')),
            ],
            options={
                'verbose_name': 'ProjectWorks',
                'verbose_name_plural': 'ProjectWorks',
            },
        ),
    ]
