# Generated by Django 3.1.7 on 2021-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_complaint_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='worker',
            name='type',
            field=models.CharField(choices=[('ISP', 'ISP'), ('OFC', 'OFC'), ('OSP', 'OSP'), ('Financial', 'Financial'), ('Warehouse', 'Warehouse'), ('Power', 'Power'), ('Maintenance', 'Maintenance'), ('Workshop', 'Workshop'), ('Administrator', 'Administrator')], max_length=20),
        ),
    ]
