# Generated by Django 3.1.7 on 2021-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_wagesheet_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
