# Generated by Django 2.2.1 on 2020-08-24 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200823_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site_name', models.CharField(max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('is_accessible', models.BooleanField(default=False, null=True)),
                ('is_surveyed', models.BooleanField(default=False, null=True)),
                ('is_accepted', models.BooleanField(default=False, null=True)),
                ('site_location', models.CharField(blank=True, max_length=150, null=True)),
                ('location_lat', models.CharField(max_length=20, null=True)),
                ('location_long', models.CharField(max_length=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('survey_date', models.DateField(null=True)),
                ('expected_end_date', models.DateField(null=True)),
                ('current_stage', models.IntegerField(default=0)),
                ('archivedStatus', models.BooleanField(default=False)),
                ('ackStatus', models.BooleanField(default=False)),
                ('ack_date', models.DateField(null=True)),
                ('survey_time', models.CharField(blank=True, max_length=255, null=True)),
                ('can_client_view_survey_reports', models.BooleanField(default=False)),
                ('email_remainder_sent', models.BooleanField(default=False)),
                ('site_contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('site_contact_phone_number', models.IntegerField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_ready_for_connection', models.BooleanField(default=False)),
                ('is_connection_request_acknowledged', models.BooleanField(default=False)),
                ('site_connection_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_fleet_on_site', models.IntegerField(blank=True, null=True)),
                ('number_of_members_on_site', models.IntegerField(blank=True, null=True)),
                ('site_image', models.FileField(blank=True, null=True, upload_to='sites/')),
                ('isp_works_complete', models.BooleanField(default=False, null=True)),
                ('osp_works_complete', models.BooleanField(default=False, null=True)),
                ('ofc_works_complete', models.BooleanField(default=False, null=True)),
                ('site_powering_complete', models.BooleanField(default=False, null=True)),
                ('original_trenching_distance', models.IntegerField(blank=True, null=True)),
                ('current_trenching_distance', models.IntegerField(blank=True, null=True)),
                ('site_drawing', models.FileField(blank=True, null=True, upload_to='drawing/')),
                ('site_address', models.TextField(blank=True, null=True)),
                ('site_usd_rate', models.IntegerField(blank=True, null=True)),
                ('site_type', models.CharField(blank=True, choices=[('single', 'Single'), ('dual', 'Dual'), ('shared', 'Shared')], max_length=150, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitePower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('material_used', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('powering_successful', models.BooleanField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_used', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitePIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.FileField(upload_to='siteimages')),
                ('lat', models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('before', 'before'), ('after', 'after')], max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='sitedocuments')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Siteboq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('estimate_quantity', models.IntegerField(blank=True, null=True)),
                ('boq_type', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteboq_site', to='projects.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
