# Generated by Django 3.1.7 on 2021-03-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210320_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wage',
            unique_together={('worker', 'activity', 'wage_sheet')},
        ),
        migrations.AlterUniqueTogether(
            name='wagesheet',
            unique_together={('supervisor_user', 'field_manager_user', 'date', 'wage_bill')},
        ),
    ]
