# Generated by Django 2.2.1 on 2020-09-04 12:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_site_siteboq_sitedocument_siteimage_sitepip_sitepower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('unit_measure', models.CharField(blank=True, max_length=10, null=True)),
                ('is_fd_underground', models.BooleanField(blank=True, default=False, null=True)),
                ('is_fd_arial', models.BooleanField(blank=True, default=False, null=True)),
                ('is_site_connection', models.BooleanField(blank=True, default=False, null=True)),
                ('is_tower_construction', models.BooleanField(blank=True, default=False, null=True)),
                ('is_lan_installation', models.BooleanField(blank=True, default=False, null=True)),
                ('is_equipment_installation', models.BooleanField(blank=True, default=False, null=True)),
                ('is_manhole_installation', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activitys',
            },
        ),
    ]
