# Generated by Django 3.1.1 on 2020-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_site_siteboq_sitedocument_siteimage_sitepip_sitepower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('next_of_kin', models.IntegerField()),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Operator', 'Operator'), ('ISP', 'ISP'), ('OFC', 'OFC'), ('Financial', 'Financial')], max_length=20)),
                ('business_unit', models.CharField(choices=[('MS', 'Managed Services'), ('CN', 'Connectivity'), ('ND', 'Network Deployment'), ('QL', 'Quality'), ('ET', 'Emerging Technologies')], max_length=2)),
            ],
        ),
    ]
