# Generated by Django 3.1.7 on 2021-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_survey_segmate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='unit_measure',
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='unit_of_measure',
            field=models.CharField(default='Meter', max_length=50),
        ),
    ]
