# Generated by Django 3.1.1 on 2020-09-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='next_of_kin',
            field=models.CharField(max_length=15),
        ),
    ]
