# Generated by Django 3.1.7 on 2021-04-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_survey_segmate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='unit_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='unit_of_measure',
            field=models.CharField(default='Meter', max_length=50),
        ),
    ]
