# Generated by Django 3.1.1 on 2020-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200904_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='national_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
