# Generated by Django 3.1.7 on 2021-04-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210422_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.unitofmeasure'),
        ),
    ]
