# Generated by Django 3.1.7 on 2021-04-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210421_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='unit_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.unitofmeasure'),
        ),
    ]
