# Generated by Django 3.1.1 on 2020-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_worker_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='national_id_document',
            field=models.FileField(default=2, upload_to='documents'),
            preserve_default=False,
        ),
    ]
