# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210421_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
