# Generated by Django 3.1.7 on 2021-05-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210426_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wage',
            options={'ordering': ('worker__name',)},
        ),
        migrations.AlterModelOptions(
            name='wagesheet',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='national_id_document',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('ISP', 'ISP'), ('OFC', 'OFC'), ('OSP', 'OSP'), ('Financial', 'Financial'), ('Warehouse', 'Warehouse'), ('Power', 'Power'), ('Maintenance', 'Maintenance'), ('Workshop', 'Workshop'), ('Administrator', 'Administrator'), ('Security', 'Security'), ('Transport', 'Transport'), ('Miscellaneous', 'Miscellaneous')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assignments', to=settings.AUTH_USER_MODEL, verbose_name='Currently Working Under'),
        ),
        migrations.AddField(
            model_name='worker',
            name='national_ID_NIN',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='national_ID_document',
            field=models.FileField(default=0, upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('ISP', 'ISP'), ('OFC', 'OFC'), ('OSP', 'OSP'), ('Financial', 'Financial'), ('Warehouse', 'Warehouse'), ('Power', 'Power'), ('Maintenance', 'Maintenance'), ('Workshop', 'Workshop'), ('Administrator', 'Administrator'), ('Security', 'Security'), ('Transport', 'Transport'), ('Miscellaneous', 'Miscellaneous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mobile_money_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.CreateModel(
            name='WorkerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('from_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_supervisor', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.worker')),
            ],
            options={
                'verbose_name': 'WorkerAssignment',
                'verbose_name_plural': 'WorkerAssignments',
            },
        ),
        migrations.CreateModel(
            name='GroupWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(to='projects.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='GroupWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.activity')),
                ('group_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.groupworker')),
                ('wage_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagesheet')),
            ],
            options={
                'unique_together': {('wage_sheet', 'group_worker', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedWageBillPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_mobile_money_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wednesday_total_amount', models.IntegerField(default=0)),
                ('thursday_total_amount', models.IntegerField(default=0)),
                ('friday_total_amount', models.IntegerField(default=0)),
                ('saturday_total_amount', models.IntegerField(default=0)),
                ('sunday_total_amount', models.IntegerField(default=0)),
                ('monday_total_amount', models.IntegerField(default=0)),
                ('tuesday_total_amount', models.IntegerField(default=0)),
                ('wage_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagebill')),
            ],
        ),
        migrations.AddField(
            model_name='wage',
            name='group_wage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.groupwage'),
        ),
        migrations.CreateModel(
            name='ConsolidatedWageBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField()),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_mobile_money_number', models.IntegerField(default=0)),
                ('worker_mobile_money_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_wages', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_deductions', models.IntegerField(default=0)),
                ('wage_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagebill')),
            ],
            options={
                'unique_together': {('wage_bill', 'worker_id')},
            },
        ),
    ]
