# Generated by Django 2.2.1 on 2020-09-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_worker_national_id_document'),
        ('projects', '0007_activity'),
    ]

    operations = [
    ]
