# Generated by Django 3.1.7 on 2021-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210426_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('ISP', 'ISP'), ('OFC', 'OFC'), ('OSP', 'OSP'), ('Financial', 'Financial'), ('Warehouse', 'Warehouse'), ('Power', 'Power'), ('Maintenance', 'Maintenance'), ('Workshop', 'Workshop'), ('Administrator', 'Administrator'), ('Security', 'Security'), ('Miscellaneous', 'Miscellaneous')], max_length=20, null=True),
        ),
    ]
