# Generated by Django 3.1.7 on 2021-05-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_worker_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='assigned_to',
        ),
    ]
