# Generated by Django 2.2.2 on 2020-09-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_boq_clientactivityrate_material_materialboqitem_serviceboqitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialboqitem',
            unique_together={('boq', 'material')},
        ),
    ]
