# Generated by Django 3.1.7 on 2021-05-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_worker_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerassignment',
            old_name='from_supervisor',
            new_name='from_supervisor_user',
        ),
    ]
