# Generated by Django 3.1.7 on 2021-05-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_worker_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerAssignment',
        ),
    ]
