# Generated by Django 3.1.7 on 2021-05-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210517_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerassignment',
            old_name='from_supervisor_user',
            new_name='from_supervisor',
        ),
    ]
