# Generated by Django 3.1.7 on 2021-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210427_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='national_id_document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
