# Generated by Django 3.1.7 on 2021-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210501_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mobile_money_name',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
    ]
