# Generated by Django 3.1.7 on 2021-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210517_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerAssignment',
        ),
    ]
