# Generated by Django 3.1.7 on 2021-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210501_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='national_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='national_id_NIN',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
