# Generated by Django 2.2.2 on 2020-09-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200917_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Survey')),
            ],
        ),
    ]
