# Generated by Django 3.1.7 on 2021-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_workerassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
