# Generated by Django 3.1.7 on 2021-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210519_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidatedwagebill',
            options={'ordering': ('worker_name',)},
        ),
    ]
