# Generated by Django 3.1.7 on 2021-05-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_workerassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerAssignment',
        ),
    ]
