# Generated by Django 2.2.2 on 2020-09-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200917_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionscope',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Survey'),
        ),
        migrations.AlterUniqueTogether(
            name='executionscope',
            unique_together={('quantity', 'survey')},
        ),
    ]
