# Generated by Django 3.1.7 on 2021-05-03 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210501_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(to='projects.Worker')),
            ],
        ),
    ]
