# Generated by Django 3.1.7 on 2021-05-16 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210501_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assignment', to=settings.AUTH_USER_MODEL, verbose_name='Currently Working Under'),
        ),
        migrations.CreateModel(
            name='ConsolidatedWageBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_money_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('wage_bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.wagebill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.worker')),
            ],
            options={
                'verbose_name': 'ConsolidatedWageBill',
                'verbose_name_plural': 'ConsolidatedWageBills',
            },
        ),
    ]
