# Generated by Django 3.1.7 on 2021-05-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210519_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidatedwagebill',
            options={'ordering': ('supervisor',)},
        ),
    ]
