# Generated by Django 3.1.7 on 2021-05-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20210517_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerAssignment',
        ),
    ]
