# Generated by Django 3.1.7 on 2021-05-04 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210503_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.activity')),
                ('group_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.groupworker')),
                ('wage_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagesheet')),
            ],
        ),
    ]
