# Generated by Django 3.1.7 on 2021-05-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20210504_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wage',
            options={'ordering': ('worker__name',)},
        ),
        migrations.AlterModelOptions(
            name='wagesheet',
            options={'ordering': ('date',)},
        ),
    ]
