# Generated by Django 3.1.7 on 2021-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_consolidatedwagebillpaymentperday_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='friday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='monday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='saturday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='sunday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='supervisor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='thursday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='tuesday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consolidatedwagebillpayment',
            name='wednesday_total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ConsolidatedWageBillPaymentPerDay',
        ),
    ]
