# Generated by Django 2.2.1 on 2020-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_predecessor_status'),
        ('projects', '0021_auto_20200918_1436'),
    ]

    operations = [
    ]
