# Generated by Django 3.1.7 on 2021-06-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210524_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['name']},
        ),
    ]
