# Generated by Django 2.2.2 on 2020-09-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge_20200919_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('field_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.FieldManager')),
            ],
        ),
    ]
