# Generated by Django 3.1.7 on 2021-05-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20210505_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='group_wage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.groupwage'),
        ),
    ]
