# Generated by Django 3.1.7 on 2021-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20210611_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
