# Generated by Django 2.2.1 on 2020-09-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost_material', models.IntegerField()),
                ('total_cost_execution', models.IntegerField()),
                ('total_cost_expense', models.IntegerField()),
                ('pip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.PIP')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='MaterialBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('budge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Budget')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Material')),
            ],
            options={
                'verbose_name': 'MaterialBudget',
                'verbose_name_plural': 'MaterialBudgets',
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Budget')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Expense')),
            ],
            options={
                'verbose_name': 'ExpenseBudget',
                'verbose_name_plural': 'ExpenseBudgets',
            },
        ),
        migrations.CreateModel(
            name='ExecutionBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Budget')),
            ],
            options={
                'verbose_name': 'ExecutionBudget',
                'verbose_name_plural': 'ExecutionBudgets',
            },
        ),
    ]
