# Generated by Django 3.1.7 on 2021-05-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_wage_group_wage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedWageBillPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_mobile_money_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wednesday_total_amount', models.IntegerField(default=0)),
                ('thursday_total_amount', models.IntegerField(default=0)),
                ('friday_total_amount', models.IntegerField(default=0)),
                ('saturday_total_amount', models.IntegerField(default=0)),
                ('sunday_total_amount', models.IntegerField(default=0)),
                ('monday_total_amount', models.IntegerField(default=0)),
                ('tuesday_total_amount', models.IntegerField(default=0)),
                ('wage_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagebill')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidatedWageBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_mobile_money_name', models.CharField(blank=True, max_length=50, null=True)),
                ('total_wages', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_deductions', models.IntegerField(default=0)),
                ('wage_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagebill')),
            ],
        ),
    ]
