# Generated by Django 2.2.1 on 2020-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_budget_executionbudget_expense_expensebudget_materialbudget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialbudget',
            old_name='budge',
            new_name='budget',
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_cost_execution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_cost_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_cost_material',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='executionbudget',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expensebudget',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialbudget',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
