# Generated by Django 3.1.7 on 2021-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_consolidatedwagebill_consolidatedwagebillperday'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedwagebill',
            name='supervisor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedwagebill',
            name='supervisor_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='consolidatedwagebill',
            unique_together={('wage_bill', 'worker_name', 'worker_mobile_money_name')},
        ),
    ]
