# Generated by Django 2.2.2 on 2020-09-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_workerteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTeamAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Team')),
            ],
        ),
    ]
