# Generated by Django 3.1.7 on 2021-06-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_wagesheet_project_manager_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagesheet',
            old_name='manager_comment',
            new_name='manager_comments',
        ),
    ]
