# Generated by Django 3.1.7 on 2021-06-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210615_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagesheet',
            old_name='manager_comments',
            new_name='manager_comment',
        ),
    ]
