# Generated by Django 2.2.2 on 2020-09-22 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_activityteamassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityteamassignment',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityteamassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityteamassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
