# Generated by Django 2.2.1 on 2020-09-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20200924_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialbudget',
            options={},
        ),
        migrations.AlterField(
            model_name='budget',
            name='pip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.PIP'),
        ),
    ]
