# Generated by Django 3.1.7 on 2021-05-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210514_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedwagebill',
            name='worker_mobile_money_number',
            field=models.IntegerField(default=0),
        ),
    ]
