# Generated by Django 3.1.7 on 2021-05-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_consolidatedwagebill_worker_mobile_money_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consolidatedwagebill',
            unique_together={('wage_bill', 'worker_name')},
        ),
    ]
