# Generated by Django 3.1.7 on 2021-06-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20210615_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
