# Generated by Django 2.2.2 on 2020-10-15 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20200922_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='supervisor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Worker'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'field_manager', 'supervisor')},
        ),
    ]
