# Generated by Django 2.2.2 on 2020-10-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20201015_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerTeam',
        ),
    ]
