# Generated by Django 3.1.7 on 2021-06-15 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_wagesheet_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='field_manager_approval_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='project_manager_approval_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='supervisor_submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
