# Generated by Django 3.1.7 on 2021-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20210517_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedwagebill',
            name='worker_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='consolidatedwagebill',
            unique_together={('wage_bill', 'worker_id')},
        ),
    ]
