# Generated by Django 3.1.7 on 2021-05-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210517_1440'),
        ('projects', '0030_auto_20210517_1011'),
    ]

    operations = [
    ]
