# Generated by Django 3.1.7 on 2021-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210615_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='field_manager_approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='project_manager_approval_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='supervisor_submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
