# Generated by Django 2.2.1 on 2020-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200930_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
