# Generated by Django 2.2.2 on 2020-10-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_delete_workerteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIPTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_work_completed', models.BooleanField(default=False)),
                ('pip_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.PIP')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Team')),
            ],
            options={
                'unique_together': {('pip_activity', 'team')},
            },
        ),
    ]
