# Generated by Django 3.1.7 on 2021-06-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20210615_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagesheet',
            options={'ordering': ('date', 'supervisor_user')},
        ),
    ]
