# Generated by Django 2.2.2 on 2020-10-15 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20201015_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipteam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pipteam',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pipteam',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
