# Generated by Django 3.1.7 on 2021-06-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20210616_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagesheet',
            options={'ordering': ('supervisor_user__first_name',)},
        ),
    ]
