# Generated by Django 3.1.7 on 2021-06-16 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20210616_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='project_manager_user',
            field=models.ForeignKey(default=133, on_delete=django.db.models.deletion.CASCADE, related_name='wage_sheet_project_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
