# Generated by Django 2.2.2 on 2020-10-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20201016_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='contact',
            new_name='mobile_money_number',
        ),
    ]
