# Generated by Django 2.2.1 on 2020-10-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_expense_rate'),
        ('projects', '0039_auto_20201016_1330'),
    ]

    operations = [
    ]
