# Generated by Django 2.2.2 on 2020-11-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_merge_20201019_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='field_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.FieldManager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Worker'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wagesheet',
            unique_together={('supervisor', 'field_manager', 'date')},
        ),
        migrations.RemoveField(
            model_name='wagesheet',
            name='team',
        ),
    ]
