# Generated by Django 2.2.2 on 2020-11-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20201124_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagesheet',
            name='segment',
        ),
    ]
