# Generated by Django 2.2.1 on 2020-11-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_delete_predecessor'),
        ('projects', '0042_remove_wagesheet_segment'),
    ]

    operations = [
    ]
