# Generated by Django 3.1.4 on 2020-12-31 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_wagesheet_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('executable_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.executionscope')),
            ],
        ),
    ]
