# Generated by Django 3.1.7 on 2021-07-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
