# Generated by Django 3.1.4 on 2020-12-31 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='executable_scope',
            new_name='execution_scope',
        ),
    ]
