# Generated by Django 2.2.1 on 2020-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_merge_20201130_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='is_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='is_project_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
