# Generated by Django 2.2.1 on 2020-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20201130_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagesheet',
            name='gm_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='gm_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='manager_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wagesheet',
            name='project_manager_comment',
            field=models.TextField(default=''),
        ),
    ]
