# Generated by Django 3.1.7 on 2021-08-17 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20210729_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldManagerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_manager_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('supervisor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
