# Generated by Django 3.1.4 on 2021-01-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
