# Generated by Django 2.2.1 on 2020-12-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20201217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='gm_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='gm_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='is_submitted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='manager_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='manager_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='project_manager_comment',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='project_manager_status',
            field=models.BooleanField(),
        ),
    ]
