# Generated by Django 3.1.4 on 2021-01-03 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_complaint_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('Fine', 'Fine'), ('Damage', 'Damage'), ('Overpayment', 'Overpayment')], max_length=12)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('wage_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.wagesheet')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.worker')),
            ],
            options={
                'unique_together': {('worker', 'wage_sheet')},
            },
        ),
    ]
