# Generated by Django 2.2.1 on 2021-01-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_deduction'),
        ('projects', '0047_auto_20201217_1852'),
    ]

    operations = [
    ]
