# Generated by Django 2.2.1 on 2021-01-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_merge_20210118_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='segment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Segment'),
        ),
    ]
