# Generated by Django 2.2.1 on 2021-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20210118_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
