# Generated by Django 2.2.2 on 2021-01-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20210118_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='unit_cost',
            field=models.IntegerField(default=0),
        ),
    ]
