# Generated by Django 2.2.1 on 2021-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20210119_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='is_manager_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wage',
            name='is_payed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wage',
            name='is_pm_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wage',
            name='is_supervisor_approved',
            field=models.BooleanField(default=True),
        ),
    ]
