# Generated by Django 2.2.2 on 2021-01-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_auto_20210124_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Activity'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wage',
            unique_together={('worker', 'activity')},
        ),
        migrations.RemoveField(
            model_name='wage',
            name='pip_activity',
        ),
    ]
