# Generated by Django 2.2.1 on 2021-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20210128_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='is_gm_approved',
            field=models.BooleanField(default=True),
        ),
    ]
