# Generated by Django 2.2.1 on 2021-02-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_wage_is_gm_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wage',
            name='is_supervisor_approved',
        ),
    ]
