# Generated by Django 2.2.1 on 2021-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_remove_wage_is_supervisor_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='is_gm_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wage',
            name='is_manager_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wage',
            name='is_payed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wage',
            name='is_pm_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='gm_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='manager_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='project_manager_status',
            field=models.BooleanField(null=True),
        ),
    ]
