# Generated by Django 2.2.1 on 2021-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20210204_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_gm_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_manager_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_payed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_pm_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_gm_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_manager_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_payed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_pm_approved',
            field=models.BooleanField(null=True),
        ),
    ]
