# Generated by Django 2.2.1 on 2021-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20210204_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='is_manager_approved',
            field=models.BooleanField(default=True),
        ),
    ]
