# Generated by Django 2.2.1 on 2021-02-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20210124_1648'),
        ('projects', '0058_auto_20210205_1023'),
    ]

    operations = [
    ]
