# Generated by Django 2.2.1 on 2021-02-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_merge_20210205_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Current', max_length=50)),
            ],
            options={
                'verbose_name': 'WageBill',
                'verbose_name_plural': 'WageBills',
                'unique_together': {('start_date', 'end_date', 'status')},
            },
        ),
    ]
