# Generated by Django 2.2.1 on 2021-02-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20210211_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagebill',
            name='status',
            field=models.CharField(default='Current', max_length=50),
        ),
    ]
