# Generated by Django 2.2.1 on 2021-02-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_wagesheet_wage_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='wage_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.WageBill'),
        ),
    ]
