# Generated by Django 2.2.1 on 2021-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20210211_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
