# Generated by Django 2.2.2 on 2021-02-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_auto_20210211_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagebill',
            options={'ordering': ['status'], 'verbose_name': 'WageBill', 'verbose_name_plural': 'WageBills'},
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Segment'),
        ),
        migrations.AlterField(
            model_name='wagesheet',
            name='wage_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.WageBill'),
        ),
    ]
