# Generated by Django 2.2.2 on 2021-02-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_auto_20210211_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wagebill',
            options={'ordering': ['status'], 'verbose_name': 'WageBill', 'verbose_name_plural': 'WageBills'},
        ),
    ]
