# Generated by Django 2.2.2 on 2021-02-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20210224_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagesheet',
            name='wage_bill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.WageBill'),
        ),
    ]
