# Generated by Django 2.2.2 on 2021-03-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20210224_1647'),
        ('projects', '0067_auto_20210225_1852'),
    ]

    operations = [
    ]
