# Generated by Django 2.2.2 on 2021-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_auto_20210301_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='mobile_money_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
