# Generated by Django 2.2.2 on 2021-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20210305_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Project Manager', 'Project Manager'), ('General Manager', 'General Manager')], max_length=50),
        ),
    ]
