# Generated by Django 2.2.2 on 2021-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20210305_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Field Manager', 'Field Manager'), ('Finance Office', 'Finance Office'), ('Project Manager', 'Project Manager'), ('General Manager', 'General Manager')], max_length=50),
        ),
    ]
