# Generated by Django 2.2.1 on 2020-08-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('adress', models.TextField()),
                ('website', models.CharField(max_length=45)),
                ('contact_person', models.CharField(max_length=45)),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
