# Generated by Django 2.2.1 on 2020-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
