# Generated by Django 2.2.2 on 2021-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210306_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile_pic',
        ),
    ]
