# Generated by Django 2.2.2 on 2021-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, max_length=45),
        ),
    ]
