# Generated by Django 2.2.2 on 2021-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('PM', 'Project Manager'), ('GM', 'General Manager')], max_length=50),
        ),
    ]
